# EssentialsX Pocketmine-MP port configuration!
# Made by: Wockgod 
# Contributers: 
# Discords: `woccck`
# You can use the `&` symbol throughout this config for color codes.

# Ban Information
ban-format: "&cYou have been banned for &6{reason}&c!"
ban-message: "&c{user} has been banned from the server."

# Gamemode Messages
# Tags: {player}, {target_player}, {gamemode}
gamemode:
  in_game_only: "&cYou must run this command in-game"
  invalid_arguments: "&cInvalid arguments: /gamemode <mode> [player]"
  invalid_gamemode: "&cInvalid gamemode"
  player_not_found: "&cPlayer '{player}' does not exist or is offline."
  no_permission: "&cYou don't have permission to change to that game mode."
  set_gamemode: "&aSet {target_player}'s game mode to {gamemode}."

# Exp Messages
# Tags: {player} {exp} {level} {levelup} {amount} {new_xp}
xp:
  in_game_only: "&cThis command must be used in-game."
  self_info: "{player} §r§6has §r§c{exp} EXP §r§6(level §r§c{level}§r§6) §r§6and needs {levelup} more exp to level up."
  no_permission: "&cYou do not have permission to use this command."
  add_usage: "&cUsage: /xp add <player> <amount>"
  player_not_found: "&cPlayer not found."
  invalid_amount: "&cAmount must be a positive integer."
  add_success: "&aAdded {amount} XP to {player}. Their new XP is {new_xp}."
  remove_usage: "&cUsage: /xp remove <player> <amount>"
  insufficient_xp: "&c{player} does not have that much XP."
  remove_success: "&aRemoved {amount} XP from {player}. Their new XP is {new_xp}."
  set_usage: "&cUsage: /xp set <player> <amount>"
  set_success: "&aSet {player}'s XP to {amount}."
  show_usage: "&cUsage: /xp show <player>"
  show_info: "{player} §r§6has §r§c{xp} EXP §r§6(level §r§c{level}§r§6) §r§6and needs {levelup} more exp to level up."
  invalid_command: "&cUsage: /xp [add|remove|set|show] <player> <amount>"

# Fly Configuration

fly:
  disabled: "&r&c&l[!] &r&cFly Disabled"
  enabled: "&r&a&l[!] &r&aFly Enabled"
